/ new lokiga / working version 1.5 /
leva84/command_line_notiz pull request #10
Opened 2020-10-05 13:06 UTC by leva84

new lokiga

2020-10-16 14:12 UTC, aya-soft requested changes

2020-10-16 14:12 UTC, aya-soft commented on lib/command.rb
> +# frozen_string_literal: true #
а зачем нам тут последняя решетка?

2020-10-16 14:12 UTC, aya-soft commented on lib/command.rb
> +  CURRENT_PATH = File.dirname(__FILE__)
не стоит в константу помещать переменные данные

2020-10-16 14:12 UTC, aya-soft commented on lib/command_registry.rb
> +  def facade
название этого метода понятно только тебе, а должно быть понятно всем.
можно взять что-то типа `command_descriptions`. А вообще имена у нас уже есть, так что можно добавить пару методов что-то типа `command_description_by_name`, `command_by_name`

2020-10-16 15:30 UTC, leva84 commented on lib/command.rb
> +# frozen_string_literal: true #
вообще без понятия, как она тутоказалась, исправил

2020-10-16 15:30 UTC, leva84 commented on lib/command.rb
> +  CURRENT_PATH = File.dirname(__FILE__)
переделал в метод

2020-10-16 15:37 UTC, leva84 commented on lib/command_registry.rb
> +  def facade
Исправлю

2020-10-20 09:47 UTC, aya-soft requested changes

2020-10-20 09:47 UTC, aya-soft commented on README.md
> +# command_line_notiz  [v1.6]
Денис, не смотря на множество правок, это у нас все та же версия программы :), так что не надо подкручивать, лучше совсем убрать эту строчку.

2020-10-20 09:47 UTC, aya-soft commented on README.md
> +  - зарегистрировать клас необходимо следующим образом - в методе `initialize` класса `App`
Убери пожалуйста почти все из этого, оно не актуально уже. Оставь 5 строчек описания, что мы тут разрабатываем. Этого достаточно для README

2020-10-20 09:47 UTC, aya-soft commented on app.rb
> +      puts '=================================================='
А может поставим `puts instruction` перед `loop`, чтобы не грузить пользователя каждый раз?

2020-10-20 09:47 UTC, aya-soft commented on app.rb
> +      print '>>'
Вот эта штука '>>' у нас не меняется никогда. Как ты думаешь куда лучше выносить то, что не меняется?

2020-10-20 09:47 UTC, aya-soft commented on lib/about.rb
> +    system("cat #{current_path} README.md")
Есть простой способ достать путь к папке проекта: [Dir.pwd](https://ruby-doc.org/core-2.7.2/Dir.html#method-c-pwd)

2020-10-20 09:47 UTC, aya-soft commented on lib/command.rb
> +  def current_path
Этого метода тут быть не должно, т.к. это потребность конкретной команды

2020-10-20 09:47 UTC, aya-soft commented on lib/command_registry.rb
> +  def commands_by_names
Смотри в чем была идея: имена команд мы можем легко достать, если создадим метод `command_names`
```ruby
def command_names
  commands.keys.sort
end
```

2020-10-20 09:47 UTC, aya-soft commented on lib/command_registry.rb
> +  def commands_by_names
Дальше мы хотим по имени доставать сам объект команды, для этого добавляем метод `command_by_name(name)`
```ruby
def command_by_name(name)
  commands[name]
end
```

2020-10-20 09:47 UTC, aya-soft commented on lib/command_registry.rb
> +  def commands_by_names
Теперь когда у нас все есть, мы можем удалить этот метод, который использовал слишком абстрактные хеши и массивы.

2020-10-20 09:47 UTC, aya-soft commented on lib/help.rb
> +  def call
А вот это (после изменений сверху) можно элегантно переписать:
```ruby
def call
  registry.command_names.each do |name|
    command = registry.command_by_name(name)
    puts "#{name} - #{command.description}"
  end
end
```

2020-10-20 09:47 UTC, aya-soft commented on lib/english_word_list.rb
> +      registry.app.start
это тут зачем ???

2020-10-20 22:52 UTC, leva84 commented on app.rb
> +      print '>>'
Константа

2020-10-21 00:40 UTC, leva84 commented on README.md
> +# command_line_notiz  [v1.6]
Убрал

2020-10-21 00:40 UTC, leva84 commented on README.md
> +  - зарегистрировать клас необходимо следующим образом - в методе `initialize` класса `App`
Убрал. Почти до исчезновения логики)

2020-10-21 00:41 UTC, leva84 commented on app.rb
> +      puts '=================================================='
Исправил

2020-10-21 00:41 UTC, leva84 commented on app.rb
> +      print '>>'
`INVITE = '>>'`

2020-10-21 00:42 UTC, leva84 commented on lib/about.rb
> +    system("cat #{current_path} README.md")
Пока что-то наисправлял, буду думать об универсальности.

2020-10-21 00:43 UTC, leva84 commented on lib/about.rb
> +    system("cat #{current_path} README.md")
Что бы прогу можно было запустить из любого каталога

2020-10-21 00:44 UTC, leva84 commented on lib/command.rb
> +  def current_path
Убрал. Мысль была о том, что бы тот кто хочет сщздавать команды уже имел такой способ под рукой

2020-10-21 00:44 UTC, leva84 commented on lib/command_registry.rb
> +  def commands_by_names
Классная идея, сам бы я со своим богажем не доехал бы точно)

2020-10-21 00:45 UTC, leva84 commented on lib/help.rb
> +  def call
Переписал)

2020-10-21 00:46 UTC, leva84 commented on lib/english_word_list.rb
> +      registry.app.start
Хотел перезапускать команду, но видно не судьба. Поставлю на выход), abort

2020-10-21 11:05 UTC, aya-soft approved these changes
Отличная работа!

2020-10-21 11:05 UTC, aya-soft commented on app.rb
> +  INVITE = '>>'
По-английски это называется `PROMPT` - подсказка командной строки

2020-10-21 11:05 UTC, merged