Added executable file repl.
leva84/command_line_notiz pull request #11
Opened 2020-10-22 06:57 UTC by leva84

Fixed files with rubocop. Changed the global variable in the App class.

2020-10-22 15:21 UTC, aya-soft requested changes

2020-10-22 15:21 UTC, aya-soft commented on repl
> +$LOAD_PATH << './lib/commands'
Вот это не надо, достаточно папку `lib` добавить. Просто будешь относительно нее указывать пути, например:
`require "commands/help"`

2020-10-22 15:21 UTC, aya-soft commented on repl
> +$LOAD_PATH << './lib'
Руби так не понимает, ему тут полный путь нужен

2020-10-22 15:21 UTC, aya-soft commented on repl
> +App.new.start
А слабо сделать просто `App.start`?

2020-10-22 15:21 UTC, aya-soft commented on lib/commands/help.rb
> +
к каждому файлу мы добавляем require тех файлов, которыми он пользуется!
тут `Command` нужен, значит добавляем:

`require "command"`

2020-10-22 17:57 UTC, leva84 commented on lib/commands/help.rb
> +
Я не то что бы спорю, просто не понимаю зачем, это же потомок Command

2020-10-22 18:15 UTC, leva84 commented on repl
> +App.new.start
Так-то да))

2020-10-22 18:16 UTC, leva84 commented on repl
> +$LOAD_PATH << './lib'
Исправил

2020-10-22 18:16 UTC, leva84 commented on repl
> +$LOAD_PATH << './lib/commands'
Исправил

2020-10-26 20:55 UTC, aya-soft commented on lib/commands/help.rb
> +
Затем, чтобы иметь возможность работать с этим файлом автономно

2020-10-26 20:57 UTC, aya-soft requested changes

2020-10-26 20:57 UTC, aya-soft commented on repl
> +$LOAD_PATH << "#{Dir.pwd}/lib"
Dir.pwd нельзя тут использовать. Этот метод вернет тебе папку, из которой ты запустил программу. Нужен универсальный прием

2020-10-26 20:57 UTC, aya-soft commented on repl
> +App.new.start
Что мешает, спрашивай :)

2020-10-27 13:20 UTC, leva84 commented on repl
> +App.new.start
Отсутствие знаний, куда посмотреть-то?)

2020-10-28 13:15 UTC, leva84 commented on lib/commands/help.rb
> +
готово

2020-10-30 06:20 UTC, aya-soft requested changes

2020-10-30 06:20 UTC, aya-soft commented on lib/commands/about.rb
> +    path = $LOAD_PATH.unshift(File.expand_path('../../README.md', __dir__))
а вот тут так делать не надо Ж) 
$LOAD_PATH - это список папок, где программа будет искать КОД, а не другие файлы.
Ты же путь к файлу строишь, тогда File.expand_path('../../README.md', __dir__) и больше ничего не надо

2020-10-30 06:20 UTC, aya-soft commented on lib/app.rb
> +      puts 'such command is not registered' unless registry.command_by_name(command)
теперь давай превратим вот это сообщение в команду Undefined и перенесем код в ее метод  call:
puts 'such command is not registered'. Получается на этом уровне мы не будем проверять есть команда или нет, мы просто ее передаем дальше: registry.run_command(command), а там уже пусть registry с ней разбирается внутри метода run_command

2020-11-03 10:42 UTC, aya-soft requested changes

2020-11-03 10:42 UTC, aya-soft commented on lib/app.rb
> +      command = gets.chomp!
Получается, что переменная command уже не нужна ;)

2020-11-03 10:42 UTC, aya-soft commented on lib/app.rb
> +    @registry.register_command('eng-wl', EnglishWordList)
три команды сверху - они дефолные, я бы вынес их в отдельный метод `register_default_commands` и вызывал его внутри CommandRegistry

2020-11-03 10:42 UTC, aya-soft commented on lib/app.rb
> +    @registry.register_command('eng-wl', EnglishWordList)
а вот команда `EnglishWordList ` уже прикладная, поэтому ее место как раз тут!

2020-11-03 11:31 UTC, leva84 commented on lib/app.rb
> +    @registry.register_command('eng-wl', EnglishWordList)
Готово). Очень круто получилось)

2020-11-03 12:39 UTC, aya-soft requested changes

2020-11-03 12:39 UTC, aya-soft commented on lib/command_registry.rb
> +  def register_default_commands
вот этот метод надо вызывать внутри в `initialize`

2020-11-03 12:39 UTC, aya-soft commented on lib/app.rb
> +    @registry.register_default_commands
Этот метод нет смысла вызывать снаружи, смотри коммент ниже как лучше

2020-11-04 11:34 UTC, aya-soft requested changes

2020-11-04 11:34 UTC, aya-soft commented on lib/app.rb
> +    <<~END
Лучше использовать понятное по смыслу слово тут `HEREDOC`,
а то у тебя получается  кругом концы (END)  как-то не логично ;)

2020-11-04 11:34 UTC, aya-soft commented on lib/app.rb
> +    END
HEREDOC

2020-11-04 11:34 UTC, aya-soft commented on lib/command_registry.rb
> +  def register_default_commands
только надо этот метод закинуть ниже в раздел `private`, мы же не хотим, чтобы его кто-то снаружи вызвал ;)

2020-11-04 11:34 UTC, aya-soft commented on lib/command_registry.rb
> +    commands['help'] = Help.new(self)
Денис, ну давай все-таки единым способом будем все делать, раз уж у нас добавляются команды методом `register_command ` так надо и тут их добавлять так же. Вот представь, что в нем что-то поменялось, что побежишь и эти 3 строчки искать и править? Зачем?

2020-11-04 11:34 UTC, aya-soft commented on lib/commands/english_word_list.rb
> +    <<~END
HEREDOC please

2020-11-04 11:34 UTC, aya-soft commented on lib/commands/english_word_list.rb
> +    END
the same

2020-11-04 21:16 UTC, aya-soft approved these changes
Бинго!

2020-11-04 22:14 UTC, merged